language: go
before_install:
  - go get -v github.com/golang/lint/golint
  - go get github.com/AsynkronIT/goring
  - go get github.com/gogo/protobuf/proto
  - go get github.com/gogo/protobuf/protoc-gen-gogo
  - go get github.com/gogo/protobuf/gogoproto
  - go get github.com/gogo/protobuf/protoc-gen-gofast
  - go get google.golang.org/grpc
  - go get github.com/gogo/protobuf/protoc-gen-gogoslick

script:
  - go test ./actor 